flowchart LR
 subgraph s1["Use Case"]
        n3(["Ask for price"])
        n4(["Book a test drive"])
        n5(["Update inventory"])
        n6(["Availability"])
        n8(["Book a test drive"])
        n9(["Ask for location"])
        n10(["Financing options"])
        n11(["Add/remove car information"])
        n12(["FAQ"])
        n13(["Evaluate Price"])
        n14(["Evaluate availability"])
        n15(["Booking slots"])
  end
    n1(["User"]) -- enquires --> n3 & n9 & n10
    n1 -- enquires for --> n4 & n6
    n2(["Admin"]) -- updates --> n5
    n1 -- ask for --> n8
    n2 -- evaluates --> n11
    n2 -- checks --> n12
    n2 -- enquires for --> n13
    n2 -- validates --> n14
    n14 -. saves updates .-> n7(["Database"])
    n2 -- books --> n15
    n15 -. saves .-> n7

    style s1 fill:#757575


